# Generated by Django 5.2.12 on 2026-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientpolicy_agent_clientpolicy_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
