# Generated by Django 5.2.12 on 2026-04-24 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('task', 'Task'), ('note', 'Note'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_to', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-performed_at'],
            },
        ),
    ]
