# Generated by Django 5.2.12 on 2026-04-24 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_category', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'covers',
                'ordering': ['-created_at'],
            },
        ),
    ]
