# Generated by Django 5.2.12 on 2026-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('coverage', models.TextField(blank=True, null=True)),
                ('premium', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generic_products',
            },
        ),
    ]
