# Generated by Django 5.2.12 on 2026-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eligibility',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
