# Generated by Django 5.2.12 on 2026-04-23 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motor Vehicle',
                'verbose_name_plural': 'Motor Vehicles',
                'ordering': ['registration_number'],
            },
        ),
    ]
