# Generated by Django 5.2.12 on 2026-04-07 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('contact', models.JSONField(default=dict)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('established', models.IntegerField()),
                ('headquarters', models.CharField(blank=True, max_length=200, null=True)),
                ('reviews', models.JSONField(default=list)),
                ('licensed', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to='companies.company')),
            ],
            options={
                'db_table': 'company_reviews',
            },
        ),
    ]
