# Generated by Django 5.2.12 on 2026-04-07 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='CompanyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branded_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('coverage', models.TextField(blank=True, null=True)),
                ('premium', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('eligibility', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'company_plans',
                'unique_together': {('company', 'product')},
            },
        ),
    ]
