# Generated by Django 5.2.12 on 2026-04-24 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=100, unique=True)),
                ('insurer', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('d_expiry', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('insurer', models.CharField(blank=True, max_length=200, null=True)),
                ('declaration_text', models.TextField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_declarations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_item', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('certificate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('certificate_no', models.CharField(max_length=100, unique=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('no_of_months', models.IntegerField(default=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
