# Generated by Django 5.2.12 on 2026-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta_branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postabranch',
            name='branch_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
