# Generated by Django 5.2.12 on 2026-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
