[tool.poetry]
name = "starzed-backend"
version = "0.1.0"
description = "Starzed Django backend"
authors = ["Starzed Team"]

[tool.poetry.dependencies]
python = "^3.14"
Django = "5.2.12"
djangorestframework = "3.17.1"
djangorestframework-simplejwt = "5.5.1"
django-cors-headers = "4.9.0"
python-dotenv = "1.2.2"
psycopg2-binary = "2.9.11"
dj-database-url = "3.1.2"
gunicorn = "23.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
