# Generated by Django 5.2.12 on 2026-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('blog_date', models.CharField(max_length=50)),
                ('read_time', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
